[package]
name = "koak"
version = "1.0.0"
authors = ["Benjamin Grange <benjamin.grange@epitech.eu>"]

[dependencies]
ansi_term = "0.9"
rustyline = "1.0.0"
llvm-sys = "0.2.1"

[dependencies.iron_llvm]
git = "https://github.com/jauhien/iron-llvm"
